[project]
name = 'stackspot'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.jackpot]
path = 'contracts/jackpot.clar'
clarity_version = 3
epoch = 3.1

[contracts.pool-pox-trait]
path = 'contracts/pool-pox-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.sim-pox]
path = 'contracts/sim-pox.clar'
clarity_version = 3
epoch = 3.1

[contracts.supported-pool-list]
path = 'contracts/supported-pool-list.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
